apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: middleware
          image: "$(AcrName).azurecr.io/aistudy/frontend:latest"
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_SERVICE_BASE_URL
              value: "$(MiddlewareServiceBaseUrl)"
            - name: REACT_APP_CLIENT_ID
              value: "$(MsalAppId)"
            - name: REACT_APP_CONTENT_GENERATOR_ENDPOINT
              value: "$(MiddlewareServiceGenerateContentEndpoint)"
            - name: REACT_APP_SERVICE_ACCESS_KEY
              value: "$(MiddlewareServiceAccessKey)"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 80
  type: ClusterIP
