apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: aistudy1.azurecr.io/aistudy/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_SERVICE_BASE_URL
              value: <MIDDLEWARE_SERVICE_BASE_URL>
            - name: REACT_APP_CLIENT_ID
              value: c23e9e28-22a3-4f63-880f-eaa88fce0503
            - name: REACT_APP_CONTENT_GENERATOR_ENDPOINT
              value: "/api/v1/generate/content"
            - name: REACT_APP_SERVICE_ACCESS_KEY
              value: "b2dd28f8a77141d5a35baf3e2f3fcd45"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
