trigger:
  branches:
    include:
      - feature/ci-test

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: ai-study-vg
  - group: ai-study-secrets

stages:
  - stage: BuildAndPush
    displayName: 'Build and Push Docker Images to ACR'
    jobs:
      - job: BuildAndPush_Backend
        displayName: 'Build and Push Backend Service'
        
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                cd backend
                chmod +x mvnw
                ./mvnw clean package -X
                cd ..
              
          - task: Docker@2
            inputs:
              containerRegistry: '$(DockerRegistry)'
              repository: '$(AcrName).azurecr.io/aistudy/backend'
              command: 'buildAndPush'
              Dockerfile: 'backend/Dockerfile'
              tags: 'latest'

  - stage: DeployToAKS
    displayName: 'Deploy Services to AKS'
    dependsOn: BuildAndPush
    jobs:
      - job: Deploy_Backend_AKS
        displayName: 'Deploy Backend to AKS'
        steps:
          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: '$(AzureSubscription)'
              azureResourceGroup: '$(ResourceGroupName)'
              kubernetesCluster: '$(AKS)'
              manifests: 'backend/backend-deployment.yml'

      